name: Dependabot
on:
  pull_request:
    paths:
      - 'go.mod'

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

permissions:
  contents: write

jobs:
  update-go-modules:
    if:  startsWith(github.head_ref, 'dependabot/')
    runs-on: ubuntu-20.04
    steps:
      - name: Set up go
        uses: actions/setup-go@84cbf8094393cdc5fe1fe1671ff2647332956b1a
        with:
          go-version: 1.18.1

      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: Update go modules
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make gomod

      - name: Commit files
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          git diff --exit-code && exit 0
          git config --local user.email actions@github.com
          git config --local user.name "GitHub Actions Dependabot Update"
          git add .
          git commit -m "Update go modules"
          git push origin "HEAD:$GITHUB_HEAD_REF"
